apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    app: echo-world
spec:
  type: ClusterIP
  ports:
  - port: 3000
    name: http
    protocol: TCP
    targetPort: 3000
  selector:
    app: echo-world
