apiVersion: v1
kind: Secret
metadata:
  name:  echo
data:
  MONGODBURL:  bW9uZ29kYjovL3VzZXI6cGFzc0Btb25nby1tb25nb2RiOjI3MDE3L2VjaG8=
  # MONGODBURL:  bW9uZ29kYjovL3VzZXI6cGFzc0Btb25nby1tb25nb2RiOjI3MDE3L2VjaG8K
type: Opaque