apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-staging
  labels:
    name: letsencrypt-staging
spec:
  acme:
    email: ic4ftp@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
      # Secret resource used to store the account's private key.
    privateKeySecretRef:
      name: letsencrypt-staging
    # Add a single challenge solver, HTTP01 using nginx
    # http01: {}
    solvers:
    - http01:
        ingress:
          class: nginx
