apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: echo-prod
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ic4ftp@gmail.com
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: echo-prod-pvt-key
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
      - http01:
          ingress:
            class: nginx